# Generated by Django 4.2.13 on 2024-10-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
    ]
