# Generated by Django 4.2.13 on 2024-10-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20241004_1244'),
    ]

    operations = [
    ]
