# Generated by Django 4.2.13 on 2024-10-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20241004_1252'),
    ]

    operations = [
    ]
