# Generated by Django 4.2.13 on 2024-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_most_popular_product_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_search__a4db0b_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='shop_produc_descrip_d5da7e_idx'),
        ),
    ]
